Repository hamsangjin/InConcert, pull requests merged in 2024-09, with the labels that each got.

#108 [Feat]: 게시글 작성 시 이미지 지우면 s3에서도 지워지게 추가, 게시글 작성 취소 시 업로드한 사진 제거
  src/main/java/com/inconcert/common/controller/ImageApiController.java
  src/main/java/com/inconcert/common/service/ImageService.java
  src/main/java/com/inconcert/domain/post/controller/InfoController.java
  src/main/java/com/inconcert/domain/post/controller/ReviewController.java
  src/main/java/com/inconcert/domain/post/service/EditService.java
  src/main/java/com/inconcert/domain/post/service/WriteService.java
  src/main/java/com/inconcert/domain/user/service/MyPageService.java
  src/main/resources/templates/board/editform.html
  src/main/resources/templates/board/writeform.html
  src/main/resources/templates/user/mypageedit.html
Labels: 🐞 버그 수정, 🛠️ 기능 구현

#109 [Refactor]: Role 관련 테이블 구조 수정
  src/main/java/com/inconcert/common/auth/CustomOAuth2UserService.java
  src/main/java/com/inconcert/common/auth/CustomUserDetailsService.java
  src/main/java/com/inconcert/common/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/inconcert/common/auth/jwt/util/JwtTokenizer.java
  src/main/java/com/inconcert/common/exception/RoleNotFoundException.java
  src/main/java/com/inconcert/common/handler/GlobalExceptionHandler.java
  src/main/java/com/inconcert/common/handler/OAuth2SuccessHandler.java
  src/main/java/com/inconcert/domain/chat/entity/ChatMessage.java
  src/main/java/com/inconcert/domain/chat/entity/ChatRoom.java
  src/main/java/com/inconcert/domain/role/entity/Role.java
  src/main/java/com/inconcert/domain/role/repository/RoleRepository.java
  src/main/java/com/inconcert/domain/user/entity/Role.java
  src/main/java/com/inconcert/domain/user/entity/User.java
  src/main/java/com/inconcert/domain/user/repository/UserRepository.java
  src/main/java/com/inconcert/domain/user/service/UserService.java
Labels: 🛠️ 리팩토링

#110 [Fix]: 게시글 작성 시 ', ", & 인코딩 처리, 이모지 처리 완료
  src/main/java/com/inconcert/domain/post/service/EditService.java
  src/main/java/com/inconcert/domain/post/service/InfoService.java
  src/main/java/com/inconcert/domain/post/service/MatchService.java
  src/main/java/com/inconcert/domain/post/service/ReviewService.java
  src/main/java/com/inconcert/domain/post/service/TransferService.java
  src/main/java/com/inconcert/domain/post/service/WriteService.java
  src/main/java/com/inconcert/domain/post/util/DateUtils.java
  src/main/java/com/inconcert/domain/post/util/HtmlUtils.java
  src/main/java/com/inconcert/domain/scraping/service/PerformanceService.java
  src/main/resources/application.yml
Labels: 🐞 버그 수정

#112 [Fix]: report 조회 비교문 오류, 동행 게시글인 경우 수정 안 되는 오류 해결
  src/main/java/com/inconcert/domain/report/repository/ReportRepository.java
  src/main/resources/application.yml
  src/main/resources/templates/board/editform.html
  src/main/resources/templates/report/reportdetail.html
Labels: 🐞 버그 수정

#113 [Test]: Chat 컨트롤러 테스트 코드 작성
  src/test/java/com/inconcert/domain/chat/ChatApiControllerTest.java
  src/test/java/com/inconcert/domain/chat/ChatControllerTest.java
  src/test/java/com/inconcert/domain/chat/ChatNotificationControllerTest.java
  src/test/java/com/inconcert/domain/chat/ChatWebSocketControllerTest.java
  src/test/java/com/inconcert/domain/comment/controller/CommentControllerTest.java
  src/test/java/com/inconcert/domain/post/controller/InfoControllerTest.java
  src/test/java/com/inconcert/domain/post/controller/MatchControllerTest.java
Labels: 💯 테스트

#114 [Refactor]: ChatRoom ManyToMany관계 변경
  src/main/java/com/inconcert/domain/chat/entity/ChatRoom.java
  src/main/java/com/inconcert/domain/chat/entity/ChatRoomUser.java
  src/main/java/com/inconcert/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/inconcert/domain/chat/repository/ChatRoomUserRepository.java
  src/main/java/com/inconcert/domain/chat/service/ChatService.java
  src/main/java/com/inconcert/domain/user/entity/User.java
  src/main/java/com/inconcert/domain/user/repository/UserRepository.java
Labels: 🛠️ 리팩토링, 💫 성능 개선

#115 [Refactor]: 로그인 유저 관련 쿼리 최적화
  src/main/java/com/inconcert/common/auth/filter/JwtAuthenticationFilter.java
  src/main/resources/static/js/home.js
Labels: 🛠️ 리팩토링, 💫 성능 개선

#116 [Test]: HomeService, ImageService 테스트 코드 작성
  build.gradle
  src/main/java/com/inconcert/common/controller/HomeApiController.java
  src/main/java/com/inconcert/common/controller/HomeController.java
  src/main/java/com/inconcert/common/service/HomeService.java
  src/main/java/com/inconcert/common/service/ImageService.java
  src/main/java/com/inconcert/domain/post/repository/InfoRepository.java
  src/main/java/com/inconcert/domain/post/service/ReviewService.java
  src/test/java/com/inconcert/common/service/HomeServiceTest.java
  src/test/java/com/inconcert/common/service/ImageServiceTest.java
Labels: 💯 테스트, 🛠️ 리팩토링

#117 [Test]: Like, Report 테스트 코드 작성
  build.gradle
  src/main/java/com/inconcert/domain/like/service/LikeService.java
  src/main/java/com/inconcert/domain/post/entity/Post.java
  src/main/java/com/inconcert/domain/report/repository/ReportRepository.java
  src/main/java/com/inconcert/domain/report/service/ReportService.java
  src/test/java/com/inconcert/domain/like/controller/LikeRestControllerTest.java
  src/test/java/com/inconcert/domain/like/service/LikeServiceTest.java
  src/test/java/com/inconcert/domain/report/controller/ReportControllerTest.java
  src/test/java/com/inconcert/domain/report/service/ReportServiceTest.java
Labels: 💯 테스트, 🛠️ 리팩토링

#118 [Test]: MyPageService 단위 테스트 코드 작성
  src/main/java/com/inconcert/domain/like/entity/Like.java
  src/main/java/com/inconcert/domain/post/entity/Post.java
  src/main/java/com/inconcert/domain/user/entity/User.java
  src/test/java/com/inconcert/domain/user/service/MyPageServiceTest.java
Labels: 💯 테스트

#119 [Test]: 알림 컨트롤러 테스트 코드 작성
  src/test/java/com/inconcert/domain/notification/NotificationControllerTest.java
Labels: 💯 테스트

#120 [Test]: UserService test 로직 작성
  src/main/java/com/inconcert/domain/user/dto/request/EmailCertificationReqDto.java
  src/main/java/com/inconcert/domain/user/dto/request/EmailCheckReqDto.java
  src/main/java/com/inconcert/domain/user/dto/request/FindIdReqDto.java
  src/main/java/com/inconcert/domain/user/dto/request/FindPasswordReqDto.java
  src/main/java/com/inconcert/domain/user/dto/request/NicknameCheckReqDto.java
  src/main/java/com/inconcert/domain/user/dto/request/PhoneNumberCheckReqDto.java
  src/main/java/com/inconcert/domain/user/dto/request/RegisterReqDto.java
  src/main/java/com/inconcert/domain/user/dto/request/UsernameCheckReqDto.java
  src/main/java/com/inconcert/domain/user/entity/User.java
  src/main/java/com/inconcert/domain/user/service/UserService.java
  src/test/java/com/inconcert/common/service/HomeServiceTest.java
  src/test/java/com/inconcert/common/service/ImageServiceTest.java
  src/test/java/com/inconcert/domain/user/service/UserServiceTest.java
Labels: 💯 테스트, 🎸 기타

#121 [Fix]: '전체' 탭에 실시간으로 알림이 반영되도록 js 수정
  src/main/java/com/inconcert/domain/notification/service/NotificationService.java
  src/main/java/com/inconcert/domain/notification/service/NotificationSseEmitters.java
  src/main/resources/templates/notification.html
Labels: 🛠️ 리팩토링

#122 [Fix]: DTO 관련 문제 해결
  build.gradle
  src/main/java/com/inconcert/common/auth/jwt/token/entity/Token.java
  src/main/java/com/inconcert/common/auth/jwt/token/repository/TokenRepository.java
  src/main/java/com/inconcert/common/auth/jwt/token/service/TokenService.java
  src/main/java/com/inconcert/common/exception/JwtExceptionCode.java
  src/main/java/com/inconcert/common/handler/OAuth2SuccessHandler.java
  src/main/java/com/inconcert/domain/user/dto/request/EmailCertificationReqDto.java
  src/main/java/com/inconcert/domain/user/dto/request/EmailCheckReqDto.java
  src/main/java/com/inconcert/domain/user/dto/request/FindIdReqDto.java
  src/main/java/com/inconcert/domain/user/dto/request/FindPasswordReqDto.java
  src/main/java/com/inconcert/domain/user/dto/request/NicknameCheckReqDto.java
  src/main/java/com/inconcert/domain/user/dto/request/PhoneNumberCheckReqDto.java
  src/main/java/com/inconcert/domain/user/dto/request/RegisterReqDto.java
  src/main/java/com/inconcert/domain/user/dto/request/UsernameCheckReqDto.java
  src/main/java/com/inconcert/domain/user/service/UserService.java
  src/main/resources/static/js/register.js
Labels: 🐞 버그 수정, 🛠️ 리팩토링

#123 [Refactor]: 동행 유저 정보 못불러오는 오류, 회원 탈퇴 시 로직 추가, 글 수정 오류 해결
  src/main/java/com/inconcert/common/service/ImageService.java
  src/main/java/com/inconcert/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/inconcert/domain/feedback/entity/Feedback.java
  src/main/java/com/inconcert/domain/feedback/repository/FeedbackRepository.java
  src/main/java/com/inconcert/domain/post/entity/Post.java
  src/main/java/com/inconcert/domain/post/service/EditService.java
  src/main/java/com/inconcert/domain/user/entity/User.java
  src/main/java/com/inconcert/domain/user/repository/UserRepository.java
  src/main/java/com/inconcert/domain/user/service/MyPageService.java
  src/main/java/com/inconcert/domain/user/service/UserService.java
Labels: 🐞 버그 수정, 🛠️ 리팩토링

#124 [Refactor]: 마이페이지 정보 수정 시 유효성 검사
  src/main/java/com/inconcert/domain/feedback/repository/FeedbackRepository.java
  src/main/java/com/inconcert/domain/user/service/MyPageService.java
  src/main/java/com/inconcert/domain/user/service/UserService.java
  src/main/resources/static/css/user/editform.css
  src/main/resources/templates/user/mypageedit.html
  src/test/java/com/inconcert/domain/user/service/MyPageServiceTest.java
Labels: 🛠️ 리팩토링

#125 [Refactor] : ChatService 클래스 수정
  src/main/java/com/inconcert/domain/chat/repository/ChatRoomUserRepository.java
  src/main/java/com/inconcert/domain/chat/service/ChatService.java
  src/main/java/com/inconcert/domain/like/service/LikeService.java
Labels: 🐞 버그 수정, 🛠️ 리팩토링

#127 [Chore]: 공연 소식 게시글에 popularity 생성해 인기순위 알고리즘 적용
  src/main/java/com/inconcert/common/service/HomeService.java
  src/main/java/com/inconcert/domain/post/entity/Post.java
  src/main/java/com/inconcert/domain/post/repository/InfoRepository.java
  src/main/java/com/inconcert/domain/scraping/service/PerformanceService.java
  src/test/java/com/inconcert/common/service/HomeServiceTest.java
Labels: 🛠️ 리팩토링, 💫 성능 개선

#128 [Fix]: 스크래핑 시 로딩중 출력 제거, sse 제거
  src/main/java/com/inconcert/common/config/auth/SecurityConfig.java
  src/main/java/com/inconcert/common/controller/HomeApiController.java
  src/main/java/com/inconcert/common/controller/HomeController.java
  src/main/java/com/inconcert/common/service/HomeService.java
  src/main/java/com/inconcert/domain/post/repository/InfoRepository.java
  src/main/java/com/inconcert/domain/scraping/service/PerformanceService.java
  src/main/java/com/inconcert/domain/scraping/service/ScrapingSseEmitters.java
  src/main/resources/static/js/home.js
  src/main/resources/templates/home.html
  src/test/java/com/inconcert/common/service/HomeServiceTest.java
Labels: 🐞 버그 수정, 🛠️ 리팩토링
