Repository hamsangjin/InConcert, pull requests merged in 2024-07, with the labels that each got.

#5 [Feat] Header, Footer 추가 및 Home과 연결
  src/main/resources/static/css/home.css
  src/main/resources/static/images/chat.png
  src/main/resources/static/images/logo.png
  src/main/resources/static/images/notification.png
  src/main/resources/static/images/profile.png
  src/main/resources/static/images/search.png
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/home.html
Labels: 🛠️ 기능 구현

#7 [Feat]: Home 뷰 페이지 구현, Header의 공연 소식/후기 구분
  src/main/resources/static/css/home.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/home.html
Labels: 🛠️ 기능 구현

#11 [Style]: Home hover 추가
  src/main/resources/static/css/home.css
Labels: 🎨 스타일

#10 [Feat]: board 뷰 페이지 구현
  src/main/resources/static/css/board/board.css
  src/main/resources/templates/board/board.html
Labels: 🛠️ 기능 구현

#13 [Chore]: User entity 수정
  src/main/java/com/inconcert/domain/user/entity/User.java
Labels: 🎸 기타

#12 [Feat]: Comment 컨트롤러, DTO, Service, Repo 추가 (불필요한 필드 삭제 / 예외처리 수정)
  src/main/java/com/inconcert/domain/comment/controller/CommentController.java
  src/main/java/com/inconcert/domain/comment/dto/CommentCreateForm.java
  src/main/java/com/inconcert/domain/comment/dto/CommentDto.java
  src/main/java/com/inconcert/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/inconcert/domain/comment/entity/Comment.java
  src/main/java/com/inconcert/domain/comment/repository/CommentRepository.java
  src/main/java/com/inconcert/domain/comment/service/CommentService.java
  src/main/java/com/inconcert/global/exception/CommentNotFoundException.java
  src/main/java/com/inconcert/global/handler/GlobalExceptionHandler.java
Labels: 🛠️ 기능 구현

#14 [Feat]: 게시글 작성 폼 구현, header에 글쓰기 버튼 추가
  src/main/resources/static/css/board/board.css
  src/main/resources/static/css/home.css
  src/main/resources/static/js/writeform.js
  src/main/resources/templates/board/board.html
  src/main/resources/templates/board/writeform.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/home.html
Labels: 🛠️ 기능 구현, 🎨 스타일
