Repository hamsangjin/InConcert, pull requests merged in 2024-08, with the labels that each got.

#15 [Feat]: writeform css 파일
  src/main/resources/static/css/board/writeform.css
Labels: 🛠️ 기능 구현

#16 [Feat]: JWT 로그인 구현
  build.gradle
  src/main/java/com/inconcert/domain/role/entity/Role.java
  src/main/java/com/inconcert/domain/role/repository/RoleRepository.java
  src/main/java/com/inconcert/domain/user/.DS_Store
  src/main/java/com/inconcert/domain/user/controller/UserApiController.java
  src/main/java/com/inconcert/domain/user/controller/UserController.java
  src/main/java/com/inconcert/domain/user/dto/request/LogInReqDto.java
  src/main/java/com/inconcert/domain/user/dto/response/LoginRspDto.java
  src/main/java/com/inconcert/domain/user/entity/Gender.java
  src/main/java/com/inconcert/domain/user/entity/InitUser.java
  src/main/java/com/inconcert/domain/user/entity/Token.java
  src/main/java/com/inconcert/domain/user/entity/User.java
  src/main/java/com/inconcert/domain/user/repository/UserRepository.java
  src/main/java/com/inconcert/domain/user/service/UserService.java
  src/main/java/com/inconcert/global/auth/CustomUserDetails.java
  src/main/java/com/inconcert/global/auth/CustomUserDetailsService.java
  src/main/java/com/inconcert/global/auth/config/SecurityConfig.java
  src/main/java/com/inconcert/global/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/inconcert/global/auth/jwt/token/JwtAuthenticationToken.java
  src/main/java/com/inconcert/global/auth/jwt/token/entity/Token.java
  src/main/java/com/inconcert/global/auth/jwt/token/repository/TokenRepository.java
  src/main/java/com/inconcert/global/auth/jwt/token/service/TokenService.java
  src/main/java/com/inconcert/global/auth/jwt/util/JwtTokenizer.java
  src/main/java/com/inconcert/global/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/inconcert/global/exception/JwtExceptionCode.java
  src/main/java/com/inconcert/global/exception/UserNotFoundException.java
  src/main/java/com/inconcert/global/handler/GlobalExceptionHandler.java
  src/main/resources/application.yml
  src/main/resources/templates/loginform.html
Labels: 🛠️ 기능 구현

#17 [Docs]: PR 템블릿 수정
  .github/Pull_Request_Template.md
Labels: 📚 문서

#18 [Style]: 회원가입 폼 구현
  src/main/resources/templates/registerform.html
Labels: 🎨 스타일

#19 [Fix]: url 경로 수정
  src/main/resources/templates/registerform.html
Labels: 🐞 버그 수정

#20 [Style]: Header 프로필 이미지 드롭다운 추가
  src/main/resources/static/css/board/board.css
  src/main/resources/static/css/board/writeform.css
  src/main/resources/static/css/home.css
  src/main/resources/templates/fragments/header.html
Labels: 🎨 스타일

#22 [Feat]: Home과 카테고리 페이지의 게시물 조회, 게시물 작성 구현
  src/main/java/com/inconcert/domain/category/entity/PostCategory.java
  src/main/java/com/inconcert/domain/category/repository/CategoryRepository.java
  src/main/java/com/inconcert/domain/category/repository/PostCategoryRepository.java
  src/main/java/com/inconcert/domain/post/controller/InfoController.java
  src/main/java/com/inconcert/domain/post/controller/MatchController.java
  src/main/java/com/inconcert/domain/post/controller/ReviewController.java
  src/main/java/com/inconcert/domain/post/controller/TransferController.java
  src/main/java/com/inconcert/domain/post/dto/PostDto.java
  src/main/java/com/inconcert/domain/post/entity/Post.java
  src/main/java/com/inconcert/domain/post/repository/InfoRepository.java
  src/main/java/com/inconcert/domain/post/repository/MatchRepository.java
  src/main/java/com/inconcert/domain/post/repository/ReviewRepository.java
  src/main/java/com/inconcert/domain/post/repository/TransferRepository.java
  src/main/java/com/inconcert/domain/post/service/InfoService.java
  src/main/java/com/inconcert/domain/post/service/MatchService.java
  src/main/java/com/inconcert/domain/post/service/ReviewService.java
  src/main/java/com/inconcert/domain/post/service/TransferService.java
  src/main/java/com/inconcert/domain/user/controller/UserController.java
  src/main/java/com/inconcert/domain/user/entity/InitUser.java
  src/main/java/com/inconcert/domain/view/entity/View.java
  src/main/java/com/inconcert/global/auth/config/SecurityConfig.java
  src/main/java/com/inconcert/global/controller/HomeController.java
  src/main/java/com/inconcert/global/exception/CategoryNotFoundException.java
  src/main/java/com/inconcert/global/exception/PostCategoryNotFoundException.java
  src/main/java/com/inconcert/global/handler/GlobalExceptionHandler.java
  src/main/java/com/inconcert/global/service/HomeService.java
  src/main/resources/templates/board/board.html
  src/main/resources/templates/board/writeform.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/home.html
  src/test/java/com/inconcert/global/service/HomeServiceTest.java
Labels: 🛠️ 기능 구현

#23 [Feat]: 회원가입 구현
  src/main/java/com/inconcert/domain/certification/common/CertificationNumber.java
  src/main/java/com/inconcert/domain/certification/entity/Certification.java
  src/main/java/com/inconcert/domain/certification/provider/EmailProvider.java
  src/main/java/com/inconcert/domain/certification/repository/CertificationRepository.java
  src/main/java/com/inconcert/domain/user/controller/UserApiController.java
  src/main/java/com/inconcert/domain/user/controller/UserController.java
  src/main/java/com/inconcert/domain/user/dto/request/CheckCertificationReqDto.java
  src/main/java/com/inconcert/domain/user/dto/request/EmailCertificationReqDto.java
  src/main/java/com/inconcert/domain/user/dto/request/EmailCheckReqDto.java
  src/main/java/com/inconcert/domain/user/dto/request/RegisterReqDto.java
  src/main/java/com/inconcert/domain/user/dto/request/UsernameCheckReqDto.java
  src/main/java/com/inconcert/domain/user/dto/response/CheckCertificationRspDto.java
  src/main/java/com/inconcert/domain/user/dto/response/EmailCertificationRspDto.java
  src/main/java/com/inconcert/domain/user/dto/response/EmailCheckRspDto.java
  src/main/java/com/inconcert/domain/user/dto/response/RegisterRspDto.java
  src/main/java/com/inconcert/domain/user/dto/response/UsernameCheckRspDto.java
  src/main/java/com/inconcert/domain/user/entity/InitUser.java
  src/main/java/com/inconcert/domain/user/entity/User.java
  src/main/java/com/inconcert/domain/user/repository/UserRepository.java
  src/main/java/com/inconcert/domain/user/service/UserService.java
  src/main/java/com/inconcert/global/auth/CustomUserDetailsService.java
  src/main/java/com/inconcert/global/auth/config/SecurityConfig.java
  src/main/java/com/inconcert/global/dto/ResponseDto.java
  src/main/java/com/inconcert/global/exception/ResponseCode.java
  src/main/java/com/inconcert/global/exception/ResponseMessage.java
  src/main/java/com/inconcert/global/exception/RoleNameNotFoundException.java
  src/main/java/com/inconcert/global/handler/GlobalExceptionHandler.java
  src/main/resources/application.yml
  src/main/resources/templates/registerform.html
Labels: 🛠️ 기능 구현, 🛠️ 리팩토링

#24 [Feat]: 카테고리 상세페이지,게시글 상세페이지 추가
  src/main/java/com/inconcert/domain/post/service/InfoService.java
  src/main/resources/static/css/board/board-detail.css
  src/main/resources/static/css/board/postdetail.css
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/postdetail.html
Labels: 🛠️ 기능 구현

#26 [Feat]: 로그인 폼 네이버 로그인 추가
  src/main/resources/templates/loginform.html
Labels: 🛠️ 기능 구현

#28 [Feat]: Mypage view 구현
  src/main/resources/static/css/user/mypage.css
  src/main/resources/templates/user/mypage.html
Labels: 🛠️ 기능 구현

#25 [Feat]: 각 게시판 별 서비스 추가
  src/main/java/com/inconcert/domain/comment/controller/CommentController.java
  src/main/java/com/inconcert/domain/comment/service/CommentService.java
  src/main/java/com/inconcert/domain/comment/service/InfoCommentService.java
  src/main/java/com/inconcert/domain/comment/service/MatchCommentService.java
  src/main/java/com/inconcert/domain/comment/service/ReviewCommentService.java
  src/main/java/com/inconcert/domain/comment/service/TransferCommentService.java
  src/test/java/com/inconcert/global/service/HomeServiceTest.java
Labels: 🛠️ 기능 구현

#29 [Feat]: home, board, board-detail, post-detail, mypage각각 로직 연결
  src/main/java/com/inconcert/domain/category/entity/Category.java
  src/main/java/com/inconcert/domain/category/entity/InitCategory.java
  src/main/java/com/inconcert/domain/category/entity/PostCategory.java
  src/main/java/com/inconcert/domain/category/repository/PostCategoryRepository.java
  src/main/java/com/inconcert/domain/post/controller/InfoController.java
  src/main/java/com/inconcert/domain/post/controller/MatchController.java
  src/main/java/com/inconcert/domain/post/controller/ReviewController.java
  src/main/java/com/inconcert/domain/post/controller/TransferController.java
  src/main/java/com/inconcert/domain/post/dto/PostDto.java
  src/main/java/com/inconcert/domain/post/entity/Post.java
  src/main/java/com/inconcert/domain/post/repository/InfoRepository.java
  src/main/java/com/inconcert/domain/post/repository/MatchRepository.java
  src/main/java/com/inconcert/domain/post/repository/ReviewRepository.java
  src/main/java/com/inconcert/domain/post/repository/TransferRepository.java
  src/main/java/com/inconcert/domain/post/service/InfoService.java
  src/main/java/com/inconcert/domain/post/service/MatchService.java
  src/main/java/com/inconcert/domain/post/service/ReviewService.java
  src/main/java/com/inconcert/domain/post/service/TransferService.java
  src/main/java/com/inconcert/domain/user/service/UserService.java
  src/main/java/com/inconcert/global/auth/config/SecurityConfig.java
  src/main/java/com/inconcert/global/controller/HomeController.java
  src/main/java/com/inconcert/global/exception/PostNotFoundException.java
  src/main/java/com/inconcert/global/service/HomeService.java
  src/main/resources/static/css/board/board-detail.css
  src/main/resources/static/css/board/board.css
  src/main/resources/static/css/board/post-detail.css
  src/main/resources/static/css/board/postdetail.css
  src/main/resources/static/css/board/writeform.css
  src/main/resources/static/css/home.css
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/board.html
  src/main/resources/templates/board/post-detail.html
  src/main/resources/templates/board/postdetail.html
  src/main/resources/templates/board/writeform.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/home.html
Labels: 🛠️ 기능 구현, 🎨 스타일, 🛠️ 리팩토링

#30 [Style] loginform css 파일 생성 및 적용
  src/main/resources/static/css/loginform.css
  src/main/resources/templates/loginform.html
Labels: 🎨 스타일

#32 [Feat]: 게시물 좋아요 구현
  src/main/java/com/inconcert/domain/like/entity/Like.java
  src/main/java/com/inconcert/domain/like/repository/LikeRepository.java
  src/main/java/com/inconcert/domain/like/service/LikeService.java
  src/main/java/com/inconcert/domain/post/controller/InfoController.java
  src/main/java/com/inconcert/domain/post/controller/InfoRestController.java
  src/main/java/com/inconcert/domain/post/controller/MatchController.java
  src/main/java/com/inconcert/domain/post/controller/MatchRestController.java
  src/main/java/com/inconcert/domain/post/controller/ReviewController.java
  src/main/java/com/inconcert/domain/post/controller/ReviewRestController.java
  src/main/java/com/inconcert/domain/post/controller/TransferController.java
  src/main/java/com/inconcert/domain/post/controller/TransferRestController.java
  src/main/java/com/inconcert/domain/post/entity/Post.java
  src/main/java/com/inconcert/domain/post/service/InfoService.java
  src/main/java/com/inconcert/domain/post/service/MatchService.java
  src/main/java/com/inconcert/domain/post/service/ReviewService.java
  src/main/java/com/inconcert/domain/post/service/TransferService.java
  src/main/java/com/inconcert/domain/user/service/UserService.java
  src/main/java/com/inconcert/global/controller/HomeController.java
  src/main/java/com/inconcert/global/exception/LikeNotFoundException.java
  src/main/java/com/inconcert/global/handler/GlobalExceptionHandler.java
  src/main/resources/static/js/board/post-detail.js
  src/main/resources/static/js/board/writeform.js
  src/main/resources/templates/board/post-detail.html
Labels: 🛠️ 기능 구현, 🛠️ 리팩토링

#33 [Style] registerform css 파일 생성 및 적용
  src/main/resources/static/css/registerform.css
  src/main/resources/templates/loginform.html
  src/main/resources/templates/registerform.html
Labels: 🎨 스타일

#34 [Refactor] response의 data를 통한 로그인/로그아웃 확인
  src/main/java/com/inconcert/domain/like/service/LikeService.java
  src/main/java/com/inconcert/domain/post/controller/InfoRestController.java
  src/main/java/com/inconcert/domain/post/controller/MatchRestController.java
  src/main/java/com/inconcert/domain/post/controller/ReviewRestController.java
  src/main/java/com/inconcert/domain/post/controller/TransferRestController.java
  src/main/java/com/inconcert/global/auth/config/SecurityConfig.java
  src/main/resources/static/css/board/post-detail.css
  src/main/resources/static/js/board/post-detail.js
  src/main/resources/templates/board/post-detail.html
Labels: 🎨 스타일, 🛠️ 리팩토링

#35 [Fix]: 공연 후기에서 게시글 작성자 닉네임 안 보이는 오류
  src/main/java/com/inconcert/global/service/HomeService.java
  src/main/resources/static/css/board/board-detail.css
Labels: 🐞 버그 수정

#36 [Fix]: home과 board 페이지에서 제목이 길면 잘리는 문제 해결
  src/main/resources/static/css/board/board.css
  src/main/resources/static/css/home.css
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/board.html
  src/main/resources/templates/home.html
Labels: 🐞 버그 수정, 🎨 스타일

#39 [Feat]: 네이버 로그인 구현
  src/main/java/com/inconcert/domain/user/controller/UserApiController.java
  src/main/java/com/inconcert/domain/user/entity/SocialLoginInfo.java
  src/main/java/com/inconcert/domain/user/entity/SocialUser.java
  src/main/java/com/inconcert/domain/user/entity/User.java
  src/main/java/com/inconcert/domain/user/service/UserService.java
  src/main/java/com/inconcert/global/auth/CustomNaverUser.java
  src/main/java/com/inconcert/global/auth/CustomOAuth2UserService.java
  src/main/java/com/inconcert/global/auth/config/SecurityConfig.java
  src/main/java/com/inconcert/global/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/inconcert/global/handler/CustomOAuth2AuthenticationFailureHandler.java
  src/main/java/com/inconcert/global/handler/OAuth2SuccessHandler.java
  src/main/resources/application.yml
  src/main/resources/templates/loginform.html
Labels: 🛠️ 기능 구현

#40 [Feat] : Comment 기능 추가
  src/main/java/com/inconcert/domain/comment/controller/CommentController.java
  src/main/java/com/inconcert/domain/comment/dto/CommentCreateForm.java
  src/main/java/com/inconcert/domain/comment/entity/Comment.java
  src/main/java/com/inconcert/domain/comment/repository/CommentRepository.java
  src/main/java/com/inconcert/domain/comment/service/CommentService.java
  src/main/java/com/inconcert/domain/comment/service/InfoCommentService.java
  src/main/java/com/inconcert/domain/comment/service/MatchCommentService.java
  src/main/java/com/inconcert/domain/comment/service/ReviewCommentService.java
  src/main/java/com/inconcert/domain/comment/service/TransferCommentService.java
  src/main/java/com/inconcert/domain/post/controller/InfoController.java
  src/main/java/com/inconcert/domain/post/entity/Post.java
  src/main/java/com/inconcert/global/auth/config/SecurityConfig.java
  src/main/resources/static/js/comment.js
  src/main/resources/templates/board/post-detail.html
Labels: 🛠️ 기능 구현, 🛠️ 리팩토링

#41 [Feat]: 게시물 카테고리 페이지 검색 구현
  src/main/java/com/inconcert/domain/like/service/LikeService.java
  src/main/java/com/inconcert/domain/post/controller/InfoController.java
  src/main/java/com/inconcert/domain/post/controller/MatchController.java
  src/main/java/com/inconcert/domain/post/controller/ReviewController.java
  src/main/java/com/inconcert/domain/post/controller/TransferController.java
  src/main/java/com/inconcert/domain/post/repository/InfoRepository.java
  src/main/java/com/inconcert/domain/post/repository/MatchRepository.java
  src/main/java/com/inconcert/domain/post/repository/ReviewRepository.java
  src/main/java/com/inconcert/domain/post/repository/TransferRepository.java
  src/main/java/com/inconcert/domain/post/service/InfoService.java
  src/main/java/com/inconcert/domain/post/service/MatchService.java
  src/main/java/com/inconcert/domain/post/service/ReviewService.java
  src/main/java/com/inconcert/domain/post/service/TransferService.java
  src/main/java/com/inconcert/domain/post/util/DateUtil.java
  src/main/java/com/inconcert/domain/user/service/UserService.java
  src/main/java/com/inconcert/global/handler/GlobalExceptionHandler.java
  src/main/resources/static/css/board/board-detail.css
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/post-detail.html
  src/main/resources/templates/board/writeform.html
Labels: 🛠️ 기능 구현, 🛠️ 리팩토링

#42 [Style]: 검색결과 페이지에 게시판 링크 추가, 머리말 한글로 변경
  src/main/java/com/inconcert/global/controller/HomeController.java
  src/main/resources/static/css/board/board-detail.css
  src/main/resources/static/css/board/post-detail.css
  src/main/resources/static/css/home.css
  src/main/resources/static/css/search-result.css
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/board.html
  src/main/resources/templates/board/post-detail.html
  src/main/resources/templates/home.html
  src/main/resources/templates/search-result.html
Labels: 🎨 스타일

#43 [Feat]: 아이디 찾기 추가
  src/main/java/com/inconcert/domain/user/controller/UserApiController.java
  src/main/java/com/inconcert/domain/user/controller/UserController.java
  src/main/java/com/inconcert/domain/user/dto/request/FindIdReqDto.java
  src/main/java/com/inconcert/domain/user/repository/UserRepository.java
  src/main/java/com/inconcert/domain/user/service/UserService.java
  src/main/java/com/inconcert/global/auth/config/SecurityConfig.java
  src/main/resources/templates/user/idform.html
Labels: 🛠️ 기능 구현

#44 [Feat]: 비밀번호 찾기 구현
  src/main/java/com/inconcert/domain/certification/common/TempPassword.java
  src/main/java/com/inconcert/domain/certification/provider/TempPasswordEmailProvider.java
  src/main/java/com/inconcert/domain/user/controller/UserApiController.java
  src/main/java/com/inconcert/domain/user/controller/UserController.java
  src/main/java/com/inconcert/domain/user/dto/request/FindPasswordReqDto.java
  src/main/java/com/inconcert/domain/user/entity/User.java
  src/main/java/com/inconcert/domain/user/repository/UserRepository.java
  src/main/java/com/inconcert/domain/user/service/UserService.java
  src/main/java/com/inconcert/global/auth/config/SecurityConfig.java
  src/main/java/com/inconcert/global/handler/CustomOAuth2AuthenticationFailureHandler.java
  src/main/java/com/inconcert/global/handler/OAuth2SuccessHandler.java
  src/main/resources/templates/loginform.html
  src/main/resources/templates/user/findpwform.html
Labels: 🛠️ 기능 구현

#45 [Feat]: 글 수정 및 삭제 구현
  src/main/java/com/inconcert/domain/post/controller/InfoController.java
  src/main/java/com/inconcert/domain/post/controller/MatchController.java
  src/main/java/com/inconcert/domain/post/controller/ReviewController.java
  src/main/java/com/inconcert/domain/post/controller/TransferController.java
  src/main/java/com/inconcert/domain/post/entity/Post.java
  src/main/java/com/inconcert/domain/post/repository/InfoRepository.java
  src/main/java/com/inconcert/domain/post/service/EditService.java
  src/main/java/com/inconcert/domain/post/service/InfoService.java
  src/main/java/com/inconcert/domain/post/service/MatchService.java
  src/main/java/com/inconcert/domain/post/service/ReviewService.java
  src/main/java/com/inconcert/domain/post/service/TransferService.java
  src/main/java/com/inconcert/global/exception/ExceptionMessage.java
  src/main/resources/templates/board/editform.html
  src/main/resources/templates/board/post-detail.html
Labels: 🛠️ 기능 구현, 🛠️ 리팩토링

#46 [Style]: 게시판 검색 시 검색 정보 불러와서 유지
  src/main/java/com/inconcert/domain/post/controller/InfoController.java
  src/main/java/com/inconcert/domain/post/controller/MatchController.java
  src/main/java/com/inconcert/domain/post/controller/ReviewController.java
  src/main/java/com/inconcert/domain/post/controller/TransferController.java
  src/main/java/com/inconcert/global/controller/HomeController.java
  src/main/resources/static/css/board/post-detail.css
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/post-detail.html
  src/main/resources/templates/fragments/header.html
Labels: 🎨 스타일

#47 [Style]: 댓글 기능 디자인 변경
  src/main/resources/static/css/board/post-detail.css
  src/main/resources/static/js/comment.js
  src/main/resources/templates/board/post-detail.html
  src/main/resources/templates/fragments/commentFragment.html
Labels: 🎨 스타일

#50 [Refactor]: Post, Comment 엔티티 content longtext 추가
  src/main/java/com/inconcert/domain/comment/entity/Comment.java
  src/main/java/com/inconcert/domain/post/entity/Post.java
  src/main/resources/static/css/board/post-detail.css
  src/main/resources/static/css/home.css
  src/main/resources/templates/board/post-detail.html
Labels: 🛠️ 리팩토링

#52 [Feat]: 게시글 작성/수정 시 이미지 업로드 및 썸네일 처리
  src/main/java/com/inconcert/domain/crawling/entity/Performance.java
  src/main/java/com/inconcert/domain/post/config/WebConfig.java
  src/main/java/com/inconcert/domain/post/controller/ImageController.java
  src/main/java/com/inconcert/domain/post/controller/InfoController.java
  src/main/java/com/inconcert/domain/post/controller/MatchController.java
  src/main/java/com/inconcert/domain/post/controller/ReviewController.java
  src/main/java/com/inconcert/domain/post/controller/TransferController.java
  src/main/java/com/inconcert/domain/post/dto/PostDto.java
  src/main/java/com/inconcert/domain/post/entity/Post.java
  src/main/java/com/inconcert/domain/post/repository/InfoRepository.java
  src/main/java/com/inconcert/domain/post/service/EditService.java
  src/main/java/com/inconcert/domain/post/service/ImageService.java
  src/main/java/com/inconcert/domain/post/service/InfoService.java
  src/main/java/com/inconcert/domain/post/service/MatchService.java
  src/main/java/com/inconcert/domain/post/service/ReviewService.java
  src/main/java/com/inconcert/domain/post/service/TransferService.java
  src/main/java/com/inconcert/domain/user/service/UserService.java
  src/main/java/com/inconcert/global/auth/config/SecurityConfig.java
  src/main/java/com/inconcert/global/exception/ExceptionMessage.java
  src/main/java/com/inconcert/global/exception/ImageUploadException.java
  src/main/java/com/inconcert/global/handler/GlobalExceptionHandler.java
  src/main/resources/application.yml
  src/main/resources/static/css/board/post-detail.css
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/editform.html
  src/main/resources/templates/board/post-detail.html
  src/main/resources/templates/board/writeform.html
  src/main/resources/templates/home.html
  src/main/resources/templates/search-result.html
Labels: 🐞 버그 수정, 🛠️ 기능 구현

#53 [Fix]: 필드가 바뀌어서 저장되는 문제 해결
  src/main/java/com/inconcert/domain/crawling/entity/Performance.java
  src/main/java/com/inconcert/domain/crawling/service/PerformanceService.java
  src/main/java/com/inconcert/global/service/CrawlingService.java
Labels: 🐞 버그 수정

#54 [Feat]: 비밀 댓글 기능 추가
  src/main/java/com/inconcert/domain/comment/controller/CommentController.java
  src/main/java/com/inconcert/domain/comment/dto/CommentCreateForm.java
  src/main/java/com/inconcert/domain/comment/dto/CommentDto.java
  src/main/java/com/inconcert/domain/comment/entity/Comment.java
  src/main/java/com/inconcert/domain/comment/service/InfoCommentService.java
  src/main/java/com/inconcert/domain/crawling/service/PerformanceService.java
  src/main/java/com/inconcert/domain/post/dto/PostDto.java
  src/main/java/com/inconcert/domain/post/entity/Post.java
  src/main/java/com/inconcert/domain/post/service/EditService.java
  src/main/resources/static/css/board/post-detail.css
  src/main/resources/static/js/comment.js
  src/main/resources/templates/board/post-detail.html
  src/main/resources/templates/fragments/commentFragment.html
Labels: 🛠️ 기능 구현, 🛠️ 리팩토링

#55 [Feat]: /Home에서 postCategory별 인기 공연 하나씩 출력
  src/main/java/com/inconcert/domain/post/repository/InfoRepository.java
  src/main/java/com/inconcert/domain/post/service/EditService.java
  src/main/java/com/inconcert/global/controller/HomeController.java
  src/main/java/com/inconcert/global/service/HomeService.java
  src/main/resources/static/css/home.css
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/home.html
Labels: 🛠️ 기능 구현, 🎨 스타일

#56 [Style]: 게시글 8개만 출력
  src/main/resources/static/css/board/board.css
  src/main/resources/static/css/home.css
  src/main/resources/templates/board/board.html
  src/main/resources/templates/home.html
Labels: 🎨 스타일

#57 [Style]: 게시글 기본 이미지 추가
  src/main/resources/templates/board/board-detail.html
Labels: 🎨 스타일

#60 [Feat]: 내 정보 수정 기능
  src/main/java/com/inconcert/domain/user/controller/MyPageController.java
  src/main/java/com/inconcert/domain/user/controller/UserApiController.java
  src/main/java/com/inconcert/domain/user/dto/request/MyPageEditReqDto.java
  src/main/java/com/inconcert/domain/user/dto/request/NicknameCheckReqDto.java
  src/main/java/com/inconcert/domain/user/dto/response/NicknameCheckRspDto.java
  src/main/java/com/inconcert/domain/user/entity/User.java
  src/main/java/com/inconcert/domain/user/repository/UserRepository.java
  src/main/java/com/inconcert/domain/user/service/MyPageService.java
  src/main/java/com/inconcert/domain/user/service/UserService.java
  src/main/java/com/inconcert/global/auth/CustomOAuth2UserService.java
  src/main/java/com/inconcert/global/exception/ResponseCode.java
  src/main/java/com/inconcert/global/exception/ResponseMessage.java
  src/main/resources/static/css/user/editform.css
  src/main/resources/templates/user/mypage.html
  src/main/resources/templates/user/mypageedit.html
Labels: 🛠️ 기능 구현

#61 [Feat]: 유저 프로필 팝업 추가
  src/main/java/com/inconcert/domain/comment/entity/Comment.java
  src/main/java/com/inconcert/domain/post/service/InfoService.java
  src/main/java/com/inconcert/domain/post/service/MatchService.java
  src/main/java/com/inconcert/domain/post/service/ReviewService.java
  src/main/java/com/inconcert/domain/post/service/TransferService.java
  src/main/java/com/inconcert/global/service/CrawlingService.java
  src/main/resources/static/css/board/post-detail.css
  src/main/resources/static/js/profile.js
  src/main/resources/templates/board/post-detail.html
  src/main/resources/templates/fragments/commentFragment.html
Labels: 🐞 버그 수정, 🛠️ 기능 구현, 🛠️ 리팩토링

#64 [Feat]: 키워드 알림
  build.gradle
  src/main/java/com/inconcert/domain/notification/controller/NotificationController.java
  src/main/java/com/inconcert/domain/notification/controller/NotificationViewController.java
  src/main/java/com/inconcert/domain/notification/dto/NotificationDto.java
  src/main/java/com/inconcert/domain/notification/entity/Notification.java
  src/main/java/com/inconcert/domain/notification/repository/NotificationRepository.java
  src/main/java/com/inconcert/domain/notification/service/NotificationService.java
  src/main/java/com/inconcert/domain/notification/service/SseEmitters.java
  src/main/java/com/inconcert/domain/post/service/InfoService.java
  src/main/java/com/inconcert/domain/post/service/MatchService.java
  src/main/java/com/inconcert/domain/post/service/ReviewService.java
  src/main/java/com/inconcert/domain/post/service/TransferService.java
  src/main/java/com/inconcert/global/auth/config/SecurityConfig.java
  src/main/java/com/inconcert/global/config/RedisConfig.java
  src/main/resources/application.yml
  src/main/resources/static/css/user/notification.css
  src/main/resources/static/images/uploads/fee56cd0-cd14-4fde-a49d-51e82af8b0d6_KakaoTalk_Photo_2024-07-25-13-23-48.png
  src/main/resources/templates/board/post-detail.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/notification.html
Labels: 🛠️ 기능 구현

#65 [Feat]: 댓글 등록순/최신순 정렬 추가
  src/main/java/com/inconcert/domain/comment/repository/CommentRepository.java
  src/main/java/com/inconcert/domain/comment/service/MatchCommentService.java
  src/main/java/com/inconcert/domain/comment/service/ReviewCommentService.java
  src/main/java/com/inconcert/domain/comment/service/TransferCommentService.java
  src/main/java/com/inconcert/domain/post/service/MatchService.java
  src/main/java/com/inconcert/domain/post/service/ReviewService.java
  src/main/java/com/inconcert/domain/post/service/TransferService.java
  src/main/resources/application.yml
  src/main/resources/static/css/board/post-detail.css
  src/main/resources/static/css/findform.css
  src/main/resources/static/css/user/editform.css
  src/main/resources/static/js/comment.js
  src/main/resources/static/js/profile.js
  src/main/resources/templates/board/post-detail.html
  src/main/resources/templates/fragments/commentFragment.html
  src/main/resources/templates/user/findpwform.html
  src/main/resources/templates/user/idform.html
  src/main/resources/templates/user/mypageedit.html
Labels: 🐞 버그 수정, 🛠️ 기능 구현, 🎨 스타일, 🛠️ 리팩토링, 💫 성능 개선

#66 [Feat]: 전체 알림, 키워드 알림, 댓글 알림, 좋아요 알림
  src/main/java/com/inconcert/domain/comment/controller/CommentController.java
  src/main/java/com/inconcert/domain/like/service/LikeService.java
  src/main/java/com/inconcert/domain/notification/controller/NotificationController.java
  src/main/java/com/inconcert/domain/notification/dto/NotificationDto.java
  src/main/java/com/inconcert/domain/notification/entity/Notification.java
  src/main/java/com/inconcert/domain/notification/repository/NotificationRepository.java
  src/main/java/com/inconcert/domain/notification/service/NotificationService.java
  src/main/java/com/inconcert/domain/post/controller/InfoController.java
  src/main/java/com/inconcert/domain/post/controller/MatchController.java
  src/main/java/com/inconcert/domain/post/controller/ReviewController.java
  src/main/java/com/inconcert/domain/post/controller/TransferController.java
  src/main/java/com/inconcert/domain/post/entity/Post.java
  src/main/java/com/inconcert/domain/post/service/EditService.java
  src/main/java/com/inconcert/domain/post/service/InfoService.java
  src/main/java/com/inconcert/domain/post/service/MatchService.java
  src/main/java/com/inconcert/domain/post/service/ReviewService.java
  src/main/java/com/inconcert/domain/post/service/TransferService.java
  src/main/java/com/inconcert/domain/user/entity/User.java
  src/main/java/com/inconcert/global/exception/ExceptionMessage.java
  src/main/java/com/inconcert/global/exception/NotificationNotFoundException.java
  src/main/java/com/inconcert/global/handler/GlobalExceptionHandler.java
  src/main/resources/static/css/board/post-detail.css
  src/main/resources/static/css/findform.css
  src/main/resources/static/css/notification.css
  src/main/resources/static/css/user/notification.css
  src/main/resources/static/images/profile.png
  src/main/resources/static/images/uploads/fee56cd0-cd14-4fde-a49d-51e82af8b0d6_KakaoTalk_Photo_2024-07-25-13-23-48.png
  src/main/resources/templates/board/post-detail.html
  src/main/resources/templates/fragments/commentFragment.html
  src/main/resources/templates/notification.html
Labels: 🐞 버그 수정, 🛠️ 기능 구현, 🎨 스타일, 🛠️ 리팩토링

#69 [Refactor]: 회원가입 이메일 인증 시 알림 창 중복 출력 제거
  src/main/java/com/inconcert/domain/user/controller/UserController.java
  src/main/java/com/inconcert/domain/user/service/UserService.java
  src/main/resources/static/css/board/post-detail.css
  src/main/resources/templates/fragments/commentFragment.html
  src/main/resources/templates/loginform.html
  src/main/resources/templates/registerform.html
  src/main/resources/templates/user/findidform.html
  src/main/resources/templates/user/findpwform.html
Labels: 🐞 버그 수정, 🎨 스타일, 🛠️ 리팩토링

#70 [Fix]: 에러 처리 추가
  src/main/java/com/inconcert/global/auth/config/SecurityConfig.java
  src/main/java/com/inconcert/global/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/inconcert/global/exception/ExceptionMessage.java
  src/main/java/com/inconcert/global/handler/CustomOAuth2AuthenticationFailureHandler.java
  src/main/java/com/inconcert/global/handler/GlobalExceptionHandler.java
Labels: 🐞 버그 수정, 🛠️ 리팩토링

#71 [Refactor]: 게시물 작성 리다이렉트 변경, 알림 실시간 오류 해결
  src/main/java/com/inconcert/domain/post/controller/InfoController.java
  src/main/java/com/inconcert/domain/post/controller/MatchController.java
  src/main/java/com/inconcert/domain/post/controller/ReviewController.java
  src/main/java/com/inconcert/domain/post/controller/TransferController.java
  src/main/java/com/inconcert/domain/post/service/InfoService.java
  src/main/java/com/inconcert/domain/post/service/MatchService.java
  src/main/java/com/inconcert/domain/post/service/ReviewService.java
  src/main/java/com/inconcert/domain/post/service/TransferService.java
  src/main/resources/templates/notification.html
Labels: 🐞 버그 수정, 🛠️ 리팩토링

#72 [Feat]: 글 작성 및 수정 시 동행 글 선택 로직, 종료날짜 불러오기, 관리자만 공연 소식 글 작성 가능
  build.gradle
  src/main/java/com/inconcert/domain/post/controller/InfoController.java
  src/main/java/com/inconcert/domain/post/controller/MatchController.java
  src/main/java/com/inconcert/domain/post/controller/ReviewController.java
  src/main/java/com/inconcert/domain/post/controller/TransferController.java
  src/main/java/com/inconcert/domain/post/entity/Post.java
  src/main/java/com/inconcert/domain/post/service/EditService.java
  src/main/java/com/inconcert/domain/post/service/InfoService.java
  src/main/java/com/inconcert/domain/post/service/MatchService.java
  src/main/java/com/inconcert/domain/post/service/ReviewService.java
  src/main/java/com/inconcert/domain/post/service/TransferService.java
  src/main/java/com/inconcert/domain/post/service/WriteService.java
  src/main/resources/templates/board/editform.html
  src/main/resources/templates/board/writeform.html
Labels: 🐞 버그 수정, 🛠️ 기능 구현, 🛠️ 리팩토링

#73 [Fix]: 글 작성 및 수정 시 종료날짜 못 불러오는 오류 해결, 동행 게시판의 경우 MBTI, 성별 검색 필터 추가
  src/main/java/com/inconcert/domain/post/controller/MatchController.java
  src/main/java/com/inconcert/domain/post/repository/MatchRepository.java
  src/main/java/com/inconcert/domain/post/service/EditService.java
  src/main/java/com/inconcert/domain/post/service/MatchService.java
  src/main/java/com/inconcert/domain/post/service/WriteService.java
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/editform.html
Labels: 🐞 버그 수정, 🛠️ 기능 구현

#74 [Perf]: Home 쿼리문 게시판별로 1개만 조회하게 변경
  src/main/java/com/inconcert/domain/category/entity/PostCategory.java
  src/main/java/com/inconcert/domain/comment/entity/Comment.java
  src/main/java/com/inconcert/domain/like/entity/Like.java
  src/main/java/com/inconcert/domain/post/controller/InfoController.java
  src/main/java/com/inconcert/domain/post/controller/MatchController.java
  src/main/java/com/inconcert/domain/post/controller/ReviewController.java
  src/main/java/com/inconcert/domain/post/controller/TransferController.java
  src/main/java/com/inconcert/domain/post/dto/PostDto.java
  src/main/java/com/inconcert/domain/post/entity/Post.java
  src/main/java/com/inconcert/domain/post/repository/InfoRepository.java
  src/main/java/com/inconcert/domain/post/repository/MatchRepository.java
  src/main/java/com/inconcert/domain/post/repository/ReviewRepository.java
  src/main/java/com/inconcert/domain/post/repository/TransferRepository.java
  src/main/java/com/inconcert/domain/post/service/InfoService.java
  src/main/java/com/inconcert/domain/post/service/MatchService.java
  src/main/java/com/inconcert/domain/post/service/ReviewService.java
  src/main/java/com/inconcert/domain/post/service/TransferService.java
  src/main/java/com/inconcert/domain/post/service/WriteService.java
  src/main/java/com/inconcert/domain/user/controller/MyPageController.java
  src/main/java/com/inconcert/domain/user/entity/User.java
  src/main/java/com/inconcert/domain/user/repository/MyPageRepostory.java
  src/main/java/com/inconcert/domain/user/service/MyPageService.java
  src/main/java/com/inconcert/global/controller/HomeController.java
  src/main/java/com/inconcert/global/repository/HomeRepository.java
  src/main/java/com/inconcert/global/service/HomeService.java
  src/main/resources/static/css/board/board-detail.css
  src/main/resources/static/css/search-result.css
  src/main/resources/static/favicon.ico
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/post-detail.html
  src/main/resources/templates/home.html
  src/main/resources/templates/search-result.html
  src/main/resources/templates/user/mypage-detail.html
  src/main/resources/templates/user/mypage.html
  src/main/resources/templates/user/mypageedit.html
Labels: 🛠️ 기능 구현, 🛠️ 리팩토링, 💫 성능 개선

#76 [Feat]: 회원가입 시 유효성 검사 추가
  src/main/java/com/inconcert/domain/user/controller/UserApiController.java
  src/main/java/com/inconcert/domain/user/dto/request/PhoneNumberCheckReqDto.java
  src/main/java/com/inconcert/domain/user/dto/request/RegisterReqDto.java
  src/main/java/com/inconcert/domain/user/dto/response/PhoneNumberCheckRspDto.java
  src/main/java/com/inconcert/domain/user/repository/UserRepository.java
  src/main/java/com/inconcert/domain/user/service/UserService.java
  src/main/java/com/inconcert/global/exception/ResponseCode.java
  src/main/java/com/inconcert/global/exception/ResponseMessage.java
  src/main/resources/static/css/registerform.css
  src/main/resources/templates/registerform.html
Labels: 🛠️ 기능 구현, 🛠️ 리팩토링

#78 [Feat]: 게시물 신고 기능, 관리자 신고 관리(게시글 삭제, 유저 정지)
  src/main/java/com/inconcert/domain/crawling/service/PerformanceService.java
  src/main/java/com/inconcert/domain/post/controller/InfoController.java
  src/main/java/com/inconcert/domain/post/controller/MatchController.java
  src/main/java/com/inconcert/domain/post/controller/ReviewController.java
  src/main/java/com/inconcert/domain/post/controller/TransferController.java
  src/main/java/com/inconcert/domain/post/dto/PostDTO.java
  src/main/java/com/inconcert/domain/post/repository/InfoRepository.java
  src/main/java/com/inconcert/domain/post/repository/MatchRepository.java
  src/main/java/com/inconcert/domain/post/repository/ReviewRepository.java
  src/main/java/com/inconcert/domain/post/repository/TransferRepository.java
  src/main/java/com/inconcert/domain/post/service/EditService.java
  src/main/java/com/inconcert/domain/post/service/InfoService.java
  src/main/java/com/inconcert/domain/post/service/MatchService.java
  src/main/java/com/inconcert/domain/post/service/ReviewService.java
  src/main/java/com/inconcert/domain/post/service/TransferService.java
  src/main/java/com/inconcert/domain/post/service/WriteService.java
  src/main/java/com/inconcert/domain/report/controller/ReportController.java
  src/main/java/com/inconcert/domain/report/dto/ReportDTO.java
  src/main/java/com/inconcert/domain/report/entity/Report.java
  src/main/java/com/inconcert/domain/report/repository/ReportRepository.java
  src/main/java/com/inconcert/domain/report/service/ReportService.java
  src/main/java/com/inconcert/domain/user/controller/MyPageController.java
  src/main/java/com/inconcert/domain/user/controller/UserApiController.java
  src/main/java/com/inconcert/domain/user/entity/User.java
  src/main/java/com/inconcert/domain/user/repository/MyPageRepostory.java
  src/main/java/com/inconcert/domain/user/service/MyPageService.java
  src/main/java/com/inconcert/domain/user/service/UserService.java
  src/main/java/com/inconcert/global/auth/config/SecurityConfig.java
  src/main/java/com/inconcert/global/controller/HomeController.java
  src/main/java/com/inconcert/global/exception/ExceptionMessage.java
  src/main/java/com/inconcert/global/exception/ReportNotFoundException.java
  src/main/java/com/inconcert/global/handler/GlobalExceptionHandler.java
  src/main/java/com/inconcert/global/repository/HomeRepository.java
  src/main/java/com/inconcert/global/service/HomeService.java
  src/main/resources/static/css/board/post-detail.css
  src/main/resources/static/css/report/reportdetail.css
  src/main/resources/static/css/report/reportform.css
  src/main/resources/static/css/report/reportlist.css
  src/main/resources/templates/board/post-detail.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/loginform.html
  src/main/resources/templates/report/reportdetail.html
  src/main/resources/templates/report/reportform.html
  src/main/resources/templates/report/reportlist.html
Labels: 🛠️ 기능 구현, 🛠️ 리팩토링

#80 [Refactor]: 예외 처리 관리, 메소드명 수정
  src/main/java/com/inconcert/domain/chat/controller/ChatController.java
  src/main/java/com/inconcert/domain/chat/controller/ChatWebSocketController.java
  src/main/java/com/inconcert/domain/chat/dto/ChatMessageDTO.java
  src/main/java/com/inconcert/domain/chat/dto/ChatRoomDTO.java
  src/main/java/com/inconcert/domain/chat/service/ChatService.java
  src/main/java/com/inconcert/domain/comment/controller/CommentController.java
  src/main/java/com/inconcert/domain/comment/dto/CommentDTO.java
  src/main/java/com/inconcert/domain/comment/entity/Comment.java
  src/main/java/com/inconcert/domain/comment/service/CommentService.java
  src/main/java/com/inconcert/domain/comment/service/InfoCommentService.java
  src/main/java/com/inconcert/domain/comment/service/MatchCommentService.java
  src/main/java/com/inconcert/domain/comment/service/ReviewCommentService.java
  src/main/java/com/inconcert/domain/comment/service/TransferCommentService.java
  src/main/java/com/inconcert/domain/crawling/service/PerformanceService.java
  src/main/java/com/inconcert/domain/like/service/LikeService.java
  src/main/java/com/inconcert/domain/notification/controller/NotificationController.java
  src/main/java/com/inconcert/domain/notification/dto/NotificationDTO.java
  src/main/java/com/inconcert/domain/notification/service/NotificationService.java
  src/main/java/com/inconcert/domain/notification/service/SseEmitters.java
  src/main/java/com/inconcert/domain/post/controller/InfoController.java
  src/main/java/com/inconcert/domain/post/controller/MatchController.java
  src/main/java/com/inconcert/domain/post/controller/ReviewController.java
  src/main/java/com/inconcert/domain/post/controller/TransferController.java
  src/main/java/com/inconcert/domain/post/service/EditService.java
  src/main/java/com/inconcert/domain/post/service/InfoService.java
  src/main/java/com/inconcert/domain/post/service/MatchService.java
  src/main/java/com/inconcert/domain/post/service/ReviewService.java
  src/main/java/com/inconcert/domain/post/service/TransferService.java
  src/main/java/com/inconcert/domain/post/service/WriteService.java
  src/main/java/com/inconcert/domain/report/controller/ReportController.java
  src/main/java/com/inconcert/domain/report/service/ReportService.java
  src/main/java/com/inconcert/domain/user/controller/MyPageController.java
  src/main/java/com/inconcert/domain/user/controller/UserApiController.java
  src/main/java/com/inconcert/domain/user/service/MyPageService.java
  src/main/java/com/inconcert/domain/user/service/UserService.java
  src/main/java/com/inconcert/global/auth/CustomOAuth2UserService.java
  src/main/java/com/inconcert/global/controller/HomeController.java
  src/main/java/com/inconcert/global/exception/ChatDeleteException.java
  src/main/java/com/inconcert/global/exception/ExceptionMessage.java
  src/main/java/com/inconcert/global/exception/ExistChatPostDeleteException.java
  src/main/java/com/inconcert/global/exception/KeywordNotFoundException.java
  src/main/java/com/inconcert/global/exception/RoleNameNotFoundException.java
  src/main/java/com/inconcert/global/exception/RoleNotFoundException.java
  src/main/java/com/inconcert/global/handler/GlobalExceptionHandler.java
  src/main/java/com/inconcert/global/handler/OAuth2SuccessHandler.java
  src/main/java/com/inconcert/global/service/CrawlingService.java
  src/main/java/com/inconcert/global/service/HomeService.java
Labels: 🛠️ 리팩토링

#81 [Refactor]: 회원가입 유효성 검사 및 인증번호 관련 문제 해결
  src/main/java/com/inconcert/domain/certification/entity/Certification.java
  src/main/java/com/inconcert/domain/user/dto/request/EmailCertificationReqDto.java
  src/main/java/com/inconcert/domain/user/dto/request/RegisterReqDto.java
  src/main/java/com/inconcert/domain/user/dto/response/RegisterRspDto.java
  src/main/java/com/inconcert/domain/user/service/UserService.java
  src/main/java/com/inconcert/global/exception/ResponseCode.java
  src/main/java/com/inconcert/global/exception/ResponseMessage.java
  src/main/resources/static/js/register.js
  src/main/resources/templates/registerform.html
Labels: 🐞 버그 수정, 🛠️ 리팩토링

#82 [Refactor]: 동행 게시글 작성 및 수정 시 종료 날짜 오늘 이후로 부터 설정 가능
  src/main/resources/templates/board/editform.html
  src/main/resources/templates/board/writeform.html
  src/main/resources/templates/report/reportdetail.html
Labels: 🛠️ 리팩토링

#83 [Fix]: 1:1 채팅이 안 되는 문제 해결
  src/main/resources/static/js/board/post-detail.js
  src/main/resources/static/js/chat/chat.js
  src/main/resources/templates/chat/room.html
Labels: 🐞 버그 수정

#85 [Feat]: SNS 공유하기 기능 추가
  src/main/java/com/inconcert/domain/comment/controller/CommentController.java
  src/main/java/com/inconcert/domain/comment/dto/CommentCreationDTO.java
  src/main/java/com/inconcert/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/inconcert/domain/comment/repository/CommentRepository.java
  src/main/java/com/inconcert/domain/comment/service/CommentService.java
  src/main/java/com/inconcert/domain/comment/service/InfoCommentService.java
  src/main/java/com/inconcert/domain/comment/service/MatchCommentService.java
  src/main/java/com/inconcert/domain/comment/service/ReviewCommentService.java
  src/main/java/com/inconcert/domain/comment/service/TransferCommentService.java
  src/main/java/com/inconcert/domain/post/controller/InfoController.java
  src/main/java/com/inconcert/domain/post/controller/MatchController.java
  src/main/java/com/inconcert/domain/post/controller/ReviewController.java
  src/main/java/com/inconcert/domain/post/controller/TransferController.java
  src/main/java/com/inconcert/global/exception/CommentDeleteUnauthorizedException.java
  src/main/java/com/inconcert/global/exception/CommentEditUnauthorizedException.java
  src/main/java/com/inconcert/global/exception/ExceptionMessage.java
  src/main/resources/application.yml
  src/main/resources/static/css/board/post-detail.css
  src/main/resources/static/images/sns/kakao.png
  src/main/resources/static/images/sns/twitter.png
  src/main/resources/static/js/board/post-detail.js
  src/main/resources/templates/board/post-detail.html
Labels: 🛠️ 기능 구현, 🛠️ 리팩토링

#86 [Chore] : 사용하지 않는 메서드 삭제
  src/main/resources/static/js/chat/chat.js
Labels: 🎸 기타

#87 [Fix]: 본인이 작성한 댓글에 알림 오는 문제 해결
  src/main/java/com/inconcert/domain/comment/controller/CommentController.java
  src/main/java/com/inconcert/domain/comment/service/CommentService.java
  src/main/java/com/inconcert/domain/comment/service/InfoCommentService.java
  src/main/java/com/inconcert/domain/comment/service/MatchCommentService.java
  src/main/java/com/inconcert/domain/comment/service/ReviewCommentService.java
  src/main/java/com/inconcert/domain/comment/service/TransferCommentService.java
Labels: 🐞 버그 수정

#88 [Style]: 각 채팅방 페이지 스타일 적용
  src/main/java/com/inconcert/domain/chat/controller/ChatApiController.java
  src/main/java/com/inconcert/domain/chat/controller/ChatController.java
  src/main/java/com/inconcert/domain/chat/dto/ChatMessageDTO.java
  src/main/java/com/inconcert/domain/chat/dto/UserDto.java
  src/main/java/com/inconcert/domain/chat/entity/ChatMessage.java
  src/main/java/com/inconcert/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/inconcert/domain/chat/service/ChatService.java
  src/main/resources/static/css/chat/list.css
  src/main/resources/static/css/chat/requests.css
  src/main/resources/static/css/chat/room.css
  src/main/resources/static/js/chat/chat.js
  src/main/resources/templates/chat/requests.html
  src/main/resources/templates/chat/room.html
Labels: 🎨 스타일, 🛠️ 리팩토링

#89 [Style]: 대댓글 위치 수정
  src/main/java/com/inconcert/domain/comment/repository/CommentRepository.java
  src/main/resources/static/css/board/post-detail.css
  src/main/resources/static/js/board/post-detail.js
Labels: 🎨 스타일

#92 [Feat]: 상호 평가 시 매너점수에 반영 로직 추가
  src/main/java/com/inconcert/domain/feedback/entity/Feedback.java
  src/main/java/com/inconcert/domain/feedback/service/FeedbackService.java
  src/main/java/com/inconcert/domain/post/repository/MatchRepository.java
  src/main/java/com/inconcert/domain/user/entity/User.java
  src/main/java/com/inconcert/domain/user/repository/UserRepository.java
  src/main/java/com/inconcert/domain/user/service/MyPageService.java
  src/main/resources/templates/board/post-detail.html
  src/main/resources/templates/fragments/commentFragment.html
  src/main/resources/templates/user/mypage.html
Labels: 🐞 버그 수정, 🛠️ 기능 구현

#93 [Refactor]: 헤더 이미지 처리 및 기본 이미지로 변경 가능
  src/main/java/com/inconcert/domain/user/controller/MyPageController.java
  src/main/java/com/inconcert/domain/user/controller/UserController.java
  src/main/java/com/inconcert/domain/user/entity/Mbti.java
  src/main/java/com/inconcert/domain/user/entity/User.java
  src/main/java/com/inconcert/domain/user/service/MyPageService.java
  src/main/java/com/inconcert/global/auth/CustomOAuth2UserService.java
  src/main/java/com/inconcert/global/auth/CustomUserDetails.java
  src/main/java/com/inconcert/global/auth/CustomUserDetailsService.java
  src/main/java/com/inconcert/global/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/inconcert/global/auth/jwt/token/entity/Token.java
  src/main/java/com/inconcert/global/handler/CustomOAuth2AuthenticationFailureHandler.java
  src/main/java/com/inconcert/global/handler/OAuth2SuccessHandler.java
  src/main/resources/application.yml
  src/main/resources/static/css/user/editform.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/user/mypageedit.html
Labels: 🐞 버그 수정, 🛠️ 리팩토링

#95 [Feat]: 전체적인 스타일 변경
  src/main/java/com/inconcert/domain/chat/controller/ChatApiController.java
  src/main/java/com/inconcert/domain/chat/controller/ChatWebSocketController.java
  src/main/java/com/inconcert/domain/chat/dto/ChatMessageDTO.java
  src/main/java/com/inconcert/domain/chat/dto/UserDto.java
  src/main/java/com/inconcert/domain/chat/repository/ChatNotificationRepository.java
  src/main/java/com/inconcert/domain/chat/service/ChatNotificationService.java
  src/main/java/com/inconcert/domain/chat/service/ChatService.java
  src/main/java/com/inconcert/domain/post/repository/InfoRepository.java
  src/main/java/com/inconcert/domain/post/repository/MatchRepository.java
  src/main/java/com/inconcert/domain/post/repository/ReviewRepository.java
  src/main/java/com/inconcert/domain/post/repository/TransferRepository.java
  src/main/java/com/inconcert/domain/post/service/MatchService.java
  src/main/java/com/inconcert/global/exception/AlreadyAppliedToChatRoomException.java
  src/main/java/com/inconcert/global/exception/ExceptionMessage.java
  src/main/resources/static/css/board/board-detail.css
  src/main/resources/static/css/board/board.css
  src/main/resources/static/css/board/post-detail.css
  src/main/resources/static/css/board/writeform.css
  src/main/resources/static/css/chat/room.css
  src/main/resources/static/css/findform.css
  src/main/resources/static/css/home.css
  src/main/resources/static/css/loginform.css
  src/main/resources/static/css/notification.css
  src/main/resources/static/css/registerform.css
  src/main/resources/static/css/report/reportdetail.css
  src/main/resources/static/css/report/reportform.css
  src/main/resources/static/css/report/reportlist.css
  src/main/resources/static/css/search-result.css
  src/main/resources/static/css/user/editform.css
  src/main/resources/static/css/user/match-list.css
  src/main/resources/static/css/user/mypage-detail.css
  src/main/resources/static/css/user/mypage.css
  src/main/resources/static/js/board/post-detail.js
  src/main/resources/static/js/chat/chat.js
  src/main/resources/templates/board/board-detail.html
  src/main/resources/templates/board/board.html
  src/main/resources/templates/board/post-detail.html
  src/main/resources/templates/board/writeform.html
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/home.html
  src/main/resources/templates/loginform.html
  src/main/resources/templates/notification.html
  src/main/resources/templates/registerform.html
  src/main/resources/templates/report/reportdetail.html
  src/main/resources/templates/report/reportform.html
  src/main/resources/templates/report/reportlist.html
  src/main/resources/templates/search-result.html
  src/main/resources/templates/user/match-list.html
  src/main/resources/templates/user/mypage-detail.html
  src/main/resources/templates/user/mypage.html
  src/main/resources/templates/user/mypageedit.html
  src/main/resources/templates/user/review-list.html
Labels: 🐞 버그 수정, 🛠️ 기능 구현, 🎨 스타일, 🛠️ 리팩토링

#97 [Feat]: 스크래핑 비동기 처리
  src/main/java/com/inconcert/domain/category/repository/PostCategoryRepository.java
  src/main/java/com/inconcert/domain/crawling/config/AsyncConfig.java
  src/main/java/com/inconcert/domain/crawling/dto/CrawledPostDTO.java
  src/main/java/com/inconcert/domain/crawling/repository/PerformanceRepository.java
  src/main/java/com/inconcert/domain/crawling/service/CrawlingSseEmitters.java
  src/main/java/com/inconcert/domain/crawling/service/PerformanceService.java
  src/main/java/com/inconcert/domain/notification/service/SseEmitters.java
  src/main/java/com/inconcert/domain/post/repository/InfoRepository.java
  src/main/java/com/inconcert/domain/post/service/InfoService.java
  src/main/java/com/inconcert/global/controller/HomeApiController.java
  src/main/java/com/inconcert/global/controller/HomeController.java
  src/main/java/com/inconcert/global/service/CrawlingService.java
  src/main/java/com/inconcert/global/service/HomeService.java
  src/main/resources/application.yml
  src/main/resources/static/js/home.js
  src/main/resources/templates/home.html
Labels: 🛠️ 기능 구현, 🛠️ 리팩토링

#98 [Fix]: IncorrectResultSizeDataAccessException 문제 해결
  src/main/java/com/inconcert/domain/post/repository/InfoRepository.java
Labels: 🐞 버그 수정

#99 [Perf]: 게시글 CRUD, Chat, Notification, Comment 쿼리 최적화 및 리팩토링
  src/main/java/com/inconcert/domain/chat/controller/ChatApiController.java
  src/main/java/com/inconcert/domain/chat/controller/ChatController.java
  src/main/java/com/inconcert/domain/chat/controller/ChatNotificationController.java
  src/main/java/com/inconcert/domain/chat/controller/ChatWebSocketController.java
  src/main/java/com/inconcert/domain/chat/dto/ChatRoomDTO.java
  src/main/java/com/inconcert/domain/chat/dto/NotificationMessage.java
  src/main/java/com/inconcert/domain/chat/dto/NotificationMessageDTO.java
  src/main/java/com/inconcert/domain/chat/dto/UserDTO.java
  src/main/java/com/inconcert/domain/chat/dto/UserDto.java
  src/main/java/com/inconcert/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/inconcert/domain/chat/repository/ChatNotificationRepository.java
  src/main/java/com/inconcert/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/inconcert/domain/chat/service/ChatNotificationService.java
  src/main/java/com/inconcert/domain/chat/service/ChatService.java
  src/main/java/com/inconcert/domain/comment/controller/CommentController.java
  src/main/java/com/inconcert/domain/comment/dto/CommentCreationDTO.java
  src/main/java/com/inconcert/domain/comment/dto/CommentDTO.java
  src/main/java/com/inconcert/domain/comment/entity/Comment.java
  src/main/java/com/inconcert/domain/comment/repository/CommentRepository.java
  src/main/java/com/inconcert/domain/comment/service/CommentService.java
  src/main/java/com/inconcert/domain/comment/service/InfoCommentService.java
  src/main/java/com/inconcert/domain/comment/service/MatchCommentService.java
  src/main/java/com/inconcert/domain/comment/service/ReviewCommentService.java
  src/main/java/com/inconcert/domain/comment/service/TransferCommentService.java
  src/main/java/com/inconcert/domain/notification/controller/NotificationController.java
  src/main/java/com/inconcert/domain/notification/entity/Notification.java
  src/main/java/com/inconcert/domain/notification/repository/NotificationRepository.java
  src/main/java/com/inconcert/domain/notification/service/NotificationService.java
  src/main/java/com/inconcert/domain/post/config/SchedulingConfig.java
  src/main/java/com/inconcert/domain/post/repository/InfoRepository.java
  src/main/java/com/inconcert/domain/post/repository/MatchRepository.java
  src/main/java/com/inconcert/domain/post/repository/ReviewRepository.java
  src/main/java/com/inconcert/domain/post/repository/TransferRepository.java
  src/main/java/com/inconcert/domain/post/service/EditService.java
  src/main/java/com/inconcert/domain/user/service/MyPageService.java
  src/main/java/com/inconcert/global/exception/ExceptionMessage.java
  src/main/java/com/inconcert/global/exception/KickException.java
  src/main/java/com/inconcert/global/exception/KickNotAllowedException.java
  src/main/java/com/inconcert/global/handler/GlobalExceptionHandler.java
  src/main/java/com/inconcert/global/repository/HomeRepository.java
  src/main/resources/static/css/board/post-detail.css
  src/main/resources/static/js/chat/chat.js
  src/main/resources/static/js/chat/request.js
  src/main/resources/templates/chat/list.html
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/fragments/commentFragment.html
  src/main/resources/templates/loginform.html
  src/main/resources/templates/notification.html
Labels: 🐞 버그 수정, 🎨 스타일, 🛠️ 리팩토링, 💫 성능 개선

#101 [Test]: 댓글/게시글 컨트롤러 테스트 코드 작성
  build.gradle
  src/main/java/com/inconcert/global/auth/config/SecurityConfig.java
  src/main/java/com/inconcert/global/swagger/OpenAPIConfig.java
  src/main/resources/application.yml
  src/test/java/com/inconcert/domain/comment/CommentControllerTest.java
  src/test/java/com/inconcert/domain/post/InfoControllerTest.java
  src/test/java/com/inconcert/domain/post/MatchControllerTest.java
Labels: 💯 테스트

#104 [Feat]: AWS S3 을 이용한 이미지 업로드 구현
  build.gradle
  src/main/java/com/inconcert/common/config/aws/AwsConfig.java
  src/main/java/com/inconcert/domain/post/controller/ImageController.java
  src/main/java/com/inconcert/domain/post/service/ImageService.java
  src/main/resources/application.yml
Labels: 🛠️ 기능 구현

#105 [Feat]: 글 작성 이미지 처리
  src/main/java/com/inconcert/domain/images/controller/ImageApiController.java
  src/main/java/com/inconcert/domain/images/service/ImageService.java
  src/main/java/com/inconcert/domain/post/controller/ImageController.java
  src/main/java/com/inconcert/domain/post/controller/InfoController.java
  src/main/java/com/inconcert/domain/post/controller/MatchController.java
  src/main/java/com/inconcert/domain/post/controller/ReviewController.java
  src/main/java/com/inconcert/domain/post/controller/TransferController.java
  src/main/java/com/inconcert/domain/post/entity/Post.java
  src/main/java/com/inconcert/domain/post/service/ImageService.java
  src/main/java/com/inconcert/domain/post/service/ReviewService.java
  src/main/java/com/inconcert/domain/post/service/WriteService.java
  src/main/java/com/inconcert/domain/scraping/service/PerformanceService.java
  src/main/java/com/inconcert/domain/user/service/MyPageService.java
  src/main/resources/application.yml
  src/main/resources/templates/board/writeform.html
  src/test/java/com/inconcert/domain/post/controller/InfoControllerTest.java
Labels: 🛠️ 기능 구현, 🛠️ 리팩토링

#106 [Fix]: 이미지 규격(가로x세로)이 넘어가면 MaxUploadSizeExceededException 오류나는 부분 리사이징을 통해 해결
  src/main/java/com/inconcert/common/controller/ImageApiController.java
  src/main/java/com/inconcert/common/service/ImageService.java
  src/main/java/com/inconcert/domain/post/service/ReviewService.java
  src/main/java/com/inconcert/domain/user/service/MyPageService.java
  src/main/resources/templates/board/writeform.html
Labels: 🐞 버그 수정, 🛠️ 리팩토링

#107 [Feat]: 글 삭제 시 S3 버킷의 이미지도 함께 삭제 기능 추가
  src/main/java/com/inconcert/common/service/ImageService.java
  src/main/java/com/inconcert/domain/post/service/MatchService.java
  src/main/java/com/inconcert/domain/post/service/TransferService.java
  src/main/resources/templates/board/writeform.html
Labels: 🛠️ 기능 구현
